#!/bin/bash

EXEC_NAME="lcd-daemon"

FILE=`pwd`/$0
CURRENT_DIR=`dirname $FILE`

EXEC_SCRIPT=systemDisplayIface.py
EXEC_COMMAND=`realpath ${CURRENT_DIR}/../${EXEC_SCRIPT}`
INITD=`realpath ${CURRENT_DIR}/1602lcd-daemon`

sed "s|#SCRIPT_COMMAND#|${EXEC_COMMAND}|" ${INITD} | \
    sed "s|#EXEC_NAME#|${EXEC_NAME}|" |
    sed "s|#EXEC_SCRIPT#|${EXEC_SCRIPT}|"  > /etc/init.d/${EXEC_NAME}
    
chmod 755 /etc/init.d/${EXEC_NAME}

update-rc.d ${EXEC_NAME} defaults
echo "Installation complated"
